'use client';

import { useState, useEffect } from 'react';
import SetupScreen from '@/components/SetupScreen';
import InterviewScreen from '@/components/InterviewScreen';
import DebriefScreen from '@/components/DebriefScreen';
import PersonaScreen from '@/components/PersonaScreen';
import SimulationScreen from '@/components/SimulationScreen';
import { AppLayout } from '@/components/AppLayout';
import { TranscriptEntry, DebriefReport, AgentId, CandidatePersona } from '@/lib/types';
import { DEFAULT_AGENT_ID } from '@/lib/agents';

export type AppStep = 'setup' | 'persona' | 'interview' | 'debrief';

export interface InterviewData {
  duration: number;
  transcript: TranscriptEntry[];
  report: DebriefReport | null;
  resume: string;
  jobDescription: string;
  selectedAgent: AgentId;
  candidatePersona: CandidatePersona | null;
}

export default function MyCareerApp() {
  const [step, setStep] = useState<AppStep>('setup');
  const [personaLoading, setPersonaLoading] = useState(false);
  const [personaError, setPersonaError] = useState<string | null>(null);
  const [simulationMode, setSimulationMode] = useState(false);
  const [interviewData, setInterviewData] = useState<InterviewData>({
    duration: 10,
    transcript: [],
    report: null,
    resume: '',
    jobDescription: '',
    selectedAgent: DEFAULT_AGENT_ID,
    candidatePersona: null,
  });

  // Load from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('mycareer-last-report');
    if (saved) {
      try {
        const report = JSON.parse(saved);
        setInterviewData(prev => ({ ...prev, report }));
      } catch (e) {
        console.error("Failed to parse saved report", e);
      }
    }
  }, []);

  const handleNavigate = (newStep: AppStep) => {
    setStep(newStep);
  };

  const handleStartInterview = async (duration: number) => {
    if (!interviewData.resume.trim() || !interviewData.jobDescription.trim()) {
      return;
    }
    setInterviewData(prev => ({
      ...prev,
      duration,
      transcript: [],
      report: null,
      candidatePersona: null,
    }));

    // Trigger persona extraction
    setPersonaLoading(true);
    setPersonaError(null);

    try {
      const response = await fetch('/api/extract-persona', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resume: interviewData.resume,
          jobDescription: interviewData.jobDescription,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to extract persona');
      }

      const persona: CandidatePersona = await response.json();
      setInterviewData(prev => ({ ...prev, candidatePersona: persona }));
      setStep('persona');
    } catch (e) {
      setPersonaError(e instanceof Error ? e.message : 'Failed to extract persona');
      setStep('persona'); // Still navigate to show error
    } finally {
      setPersonaLoading(false);
    }
  };

  const handleFinishInterview = async (
    transcript: TranscriptEntry[],
    report: DebriefReport | null
  ) => {
    console.log('[MyCareerApp] handleFinishInterview called');
    console.log('[MyCareerApp] transcript length:', transcript.length);
    console.log('[MyCareerApp] report:', report ? 'received' : 'null');

    // Reset simulation mode when returning to debrief
    setSimulationMode(false);

    // Set step to debrief immediately so user sees loading state
    setStep('debrief');

    if (report) {
      // Report already generated by InterviewScreen
      setInterviewData(prev => ({
        ...prev,
        transcript,
        report,
      }));
      localStorage.setItem('mycareer-last-report', JSON.stringify(report));
    } else {
      // Fallback: generate debrief here if not done in InterviewScreen
      // This shouldn't normally happen but provides resilience
      console.log('[MyCareerApp] Generating debrief as fallback...');
      const { generateDebrief } = await import('@/lib/debriefGenerator');
      try {
        const generatedReport = await generateDebrief(transcript);
        setInterviewData(prev => ({
          ...prev,
          transcript,
          report: generatedReport,
        }));
        localStorage.setItem('mycareer-last-report', JSON.stringify(generatedReport));
      } catch (e) {
        console.error("[MyCareerApp] Failed to generate report", e);
        setInterviewData(prev => ({
          ...prev,
          transcript,
          report: null,
        }));
      }
    }
  };

  const handleResumeChange = (text: string) => {
    setInterviewData(prev => ({ ...prev, resume: text }));
  };

  const handleJobDescriptionChange = (text: string) => {
    setInterviewData(prev => ({ ...prev, jobDescription: text }));
  };

  const handleAgentChange = (agentId: AgentId) => {
    setInterviewData(prev => ({ ...prev, selectedAgent: agentId }));
  };

  const handlePersonaChange = (persona: CandidatePersona) => {
    setInterviewData(prev => ({ ...prev, candidatePersona: persona }));
  };

  const handleProceedToSimulation = () => {
    // Per D-01: Simulation starts immediately after persona confirmation
    setSimulationMode(true);
    setStep('interview');
  };

  const handleFileParsed = (type: 'resume' | 'jd', text: string) => {
    if (type === 'resume') {
      setInterviewData(prev => ({ ...prev, resume: text }));
    } else {
      setInterviewData(prev => ({ ...prev, jobDescription: text }));
    }
  };

  const handleReset = () => {
    setSimulationMode(false);
    setStep('setup');
  };

  return (
    <AppLayout
      currentStep={step}
      onNavigate={handleNavigate}
      disabledSteps={[
        // Persona disabled until user has entered resume and JD
        ...(step === 'setup' && (!interviewData.resume.trim() || !interviewData.jobDescription.trim()) ? ['persona' as const] : []),
        // Interview disabled until persona is confirmed (from persona step)
        ...(step !== 'persona' && step !== 'interview' && step !== 'debrief' ? ['interview' as const] : []),
        // Results disabled until interview completed (has report)
        ...(!interviewData.report ? ['debrief' as const] : []),
      ]}
    >
      <div className="flex-1 flex flex-col min-h-0">
        {step === 'setup' && (
          <SetupScreen
            onStart={handleStartInterview}
            lastReport={interviewData.report}
            onViewLastReport={() => setStep('debrief')}
            resume={interviewData.resume}
            jobDescription={interviewData.jobDescription}
            selectedAgent={interviewData.selectedAgent}
            onResumeChange={handleResumeChange}
            onJobDescriptionChange={handleJobDescriptionChange}
            onAgentChange={handleAgentChange}
            onFileParsed={handleFileParsed}
          />
        )}
        {step === 'persona' && (
          <PersonaScreen
            persona={interviewData.candidatePersona}
            isLoading={personaLoading}
            error={personaError}
            onPersonaChange={handlePersonaChange}
            onProceed={handleProceedToSimulation}
            onBack={() => setStep('setup')}
          />
        )}
        {step === 'interview' && (
          simulationMode ? (
            <SimulationScreen
              candidatePersona={interviewData.candidatePersona!}
              selectedAgent={interviewData.selectedAgent}
              resume={interviewData.resume}
              jobDescription={interviewData.jobDescription}
              onFinish={handleFinishInterview}
            />
          ) : (
            <InterviewScreen
              duration={interviewData.duration}
              onFinish={handleFinishInterview}
              resume={interviewData.resume}
              jobDescription={interviewData.jobDescription}
              selectedAgent={interviewData.selectedAgent}
            />
          )
        )}
        {step === 'debrief' && (
          <DebriefScreen
            report={interviewData.report}
            onReset={handleReset}
          />
        )}
      </div>
    </AppLayout>
  );
}